name: Build and Release Docker Image

on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: check if package.json version is updated by comparing with the previous commit
        run: |
          OLD_VERSION=$(git show HEAD~1:package.json | jq -r .version)
          NEW_VERSION=$(jq -r .version package.json)
          if [ "$OLD_VERSION" = "$NEW_VERSION" ]; then
            echo "Error: package.json version is not updated"
            exit 1
          fi

      - name: Install pnpm
        run: npm install -g pnpm

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Build project
        run: pnpm run build

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: set lower case owner name
        run: |
          echo "OWNER_LC=${OWNER,,}" >>${GITHUB_ENV}
        env:
          OWNER: "${{ github.repository_owner }}"

      - name: Build Docker image
        run: docker build -t ghcr.io/${OWNER_LC}/moodle-mcp-server:${{ github.ref_name }} .

      - name: Push Docker image
        run: docker push ghcr.io/${OWNER_LC}/moodle-mcp-server:${{ github.ref_name }}
